
POST http://localhost:8000/api/rooms/85d9a08b-60cd-443b-8799-ad90b75e8317/performance/ HTTP/1.1
Content-Type: application/json

{
    "player_id":"3a6e83a0-1c1b-40fd-858e-4184545ff99e",
    "tune_id": 2
}

###
GET http://localhost:8000/api/rooms/85d9a08b-60cd-443b-8799-ad90b75e8317/performance/ HTTP/1.1
Content-Type: application/json

###
GET http://localhost:8000/api/rooms/85d9a08b-60cd-443b-8799-ad90b75e8317/performance/{performance}/ HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:8000/api/rooms/85d9a08b-60cd-443b-8799-ad90b75e8317/performance/{performance}/ HTTP/1.1
Content-Type: application/json

{
  "player_id_set":[15,16,17],
  "tune_id":2
}

###
PUT http://localhost:8000/api/rooms/85d9a08b-60cd-443b-8799-ad90b75e8317/performance/{performance}/ HTTP/1.1
Content-Type: application/json

{
  "player_id_set":[15,16,17],
  "tune_id":2
}


###
PATCH http://localhost:8000/api/rooms/85d9a08b-60cd-443b-8799-ad90b75e8317/performance/{performance}/ HTTP/1.1
Content-Type: application/json

{
  "player_id_set":[15,16,17],
  "tune_id":1
}


###
DELETE http://localhost:8000/api/rooms/85d9a08b-60cd-443b-8799-ad90b75e8317/performance/{performance}/ HTTP/1.1
Content-Type: application/json

{
  "player_id_set":[15,16],
  "tune_id": 1
}