# Generated by Django 3.0.2 on 2020-04-20 06:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.UUIDField()),
                ('tune_id', models.UUIDField()),
                ('room_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('part', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[(1, 'participating'), (2, 'breaking'), (3, 'left')], default='participating', max_length=32)),
                ('room_id', models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tune',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('playing_key', models.CharField(choices=[(1, 'C'), (2, 'C#'), (3, 'D♭'), (4, 'D'), (5, 'D#'), (6, 'E♭'), (7, 'E'), (8, 'F'), (9, 'F#'), (10, 'G♭'), (11, 'G'), (12, 'G#'), (13, 'A♭'), (14, 'A'), (15, 'A#'), (16, 'B♭'), (17, 'B')], default='unassigned', max_length=32)),
                ('status', models.CharField(choices=[(1, 'notyet'), (2, 'next'), (3, 'completed')], default='notyet', max_length=32)),
                ('room_id', models.UUIDField()),
            ],
        ),
    ]
