# Generated by Django 3.0.2 on 2020-04-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.IntegerField(choices=[(1, 'participating'), (2, 'breaking'), (3, 'left')], default=1, max_length=32),
        ),
    ]
