# Generated by Django 3.0.2 on 2020-04-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20200422_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='playing_key',
            field=models.IntegerField(choices=[(0, 'unassigned'), (1, 'C'), (2, 'D♭'), (3, 'D'), (4, 'E♭'), (5, 'E'), (6, 'F'), (7, 'G♭'), (8, 'G'), (9, 'A♭'), (10, 'A'), (11, 'B♭'), (12, 'B')], default=0),
        ),
        migrations.AlterField(
            model_name='tune',
            name='status',
            field=models.IntegerField(choices=[(0, 'notyet'), (1, 'next'), (2, 'completed')], default=0),
        ),
    ]
